# Generated by Django 3.2.3 on 2021-05-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20210526_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name', '-short_name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
