# Generated by Django 3.2.3 on 2021-05-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hability', models.CharField(max_length=50, verbose_name='Hability')),
            ],
            options={
                'verbose_name': 'Hability',
                'verbose_name_plural': 'Employer habilities',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name', '-job'], 'verbose_name': 'Mi empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'job')},
        ),
    ]
