# Generated by Django 3.2.3 on 2021-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210527_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilities',
            new_name='Hability',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilities',
            field=models.ManyToManyField(to='persona.Hability'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
