# Generated by Django 3.2.3 on 2021-05-27 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210527_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cv',
            field=ckeditor.fields.RichTextField(default='text'),
            preserve_default=False,
        ),
    ]
